### ISSUE TITLE
Sorry for the 3rd time but i found a bug

### ISSUE THREAD

**Issue by XDRmc** [request-plugins-for-free/SpeedBridge#66]
When i do /join (without numbers at back so it should random join) on console this happens: 
[18:56:03 INFO]: XDRmc_YT issued server command: /join
[18:56:03 ERROR]: [SpeedBridge] [ACF] Exception in command: join
[18:56:03 ERROR]: [SpeedBridge] [ACF] java.lang.NullPointerException: Cannot invoke "me.tofpu.speedbridge.api.island.mode.Mode.identifier()" because the return value of "me.tofpu.speedbridge.api.island.Island.mode()" is null
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.island.service.IslandServiceImpl.getAvailableIslands(IslandServiceImpl.java:75)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.game.service.GameServiceImpl.join(GameServiceImpl.java:179)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.game.service.GameServiceImpl.join(GameServiceImpl.java:139)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.command.sub.MainCommand.onJoin(MainCommand.java:109)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.command.sub.MainCommand.onJoin(MainCommand.java:61)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.acf.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.acf.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.acf.commands.BaseCommand.execute(BaseCommand.java:513)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.acf.commands.RootCommand.execute(RootCommand.java:99)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at speedbridge-1.2.3.jar//me.tofpu.speedbridge.acf.commands.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2257)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2168)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.chat(CraftPlayer.java:642)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at Citizens-2.0.28-b2362.jar//net.citizensnpcs.trait.CommandTrait$NPCCommand.run(CommandTrait.java:439)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at Citizens-2.0.28-b2362.jar//net.citizensnpcs.trait.CommandTrait$1$3.run(CommandTrait.java:248)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at Citizens-2.0.28-b2362.jar//net.citizensnpcs.trait.CommandTrait$1.runCommand(CommandTrait.java:253)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at Citizens-2.0.28-b2362.jar//net.citizensnpcs.trait.CommandTrait$1.run(CommandTrait.java:219)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at Citizens-2.0.28-b2362.jar//net.citizensnpcs.trait.CommandTrait.dispatch(CommandTrait.java:260)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at Citizens-2.0.28-b2362.jar//net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:498)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor328.execute(Unknown Source)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2422)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2472)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(PacketPlayInUseEntity.java:131)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2414)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[18:56:03 ERROR]: [SpeedBridge] [ACF]   at java.base/java.lang.Thread.run(Thread.java:831)

I am running java16 and a 1.17.1 server if that helps. also it says "I'm sorry, but there was an error performing this command"

**Comment by Tofpu** [comment]
No need to apologize, feel free to repot bugs as much as you'd like :)

Could you show your settings.yml, please?

**Comment by XDRmc** [comment]
ok wait

**Comment by XDRmc** [comment]
[settings.zip](https://github.com/request-plugins-for-free/SpeedBridge/files/7160944/settings.zip)
its is zip file. github dosent support  yaml apparently

**Comment by Tofpu** [comment]
Thanks for the settings, I believe I fixed the error.

The reason why it wouldn't work is that the island wasn't in a mode (category) which I haven't accounted for that hence the error.

Do you mind testing out the new version before I publish it? if you can't, no problem at all

**Comment by XDRmc** [comment]
ok thats fine!

**Comment by XDRmc** [comment]
I am trying to make a setup so i need this plugin xD

**Comment by Tofpu** [comment]
If you do not mind, here's the patched version. be sure to use the jar that is the biggest in terms of size. (also delete your old er version of the plugin)

https://github.com/request-plugins-for-free/SpeedBridge/suites/3763439163/artifacts/92508695

**Comment by XDRmc** [comment]
witch one do i put in

**Comment by Tofpu** [comment]
The one that is bigger in terms of size

**Comment by XDRmc** [comment]
ok i put the one thats none original and it work! thank you.

**Comment by Tofpu** [comment]
I'm glad to hear that, thank you once again for reporting the bug! :)
